### PR TITLE
Add Sum row to allocation table report

### PR DESCRIPTION
**Pull request by raabdesselam**

### CODE REVIEW

**Comment by dduponchel** [comment]
As seen together, you compute the sum for the current filter and the current page while you should compute it for the current filter and all pages.

**Comment by thomastosoni** [comment]
@stephane-mics what do we do with this?

**Comment by thomastosoni** [comment]
4 months and still going strong :+1:

**Comment by raabdesselam** [comment]
Now, the function of SUM count the sum of conversions and ratio to spend for all elements in the filter, not only the sum per page.

We need to discuss where to make the sum fields , above or bellow the table.

**Comment by thomastosoni** [comment]
Doesn't start, you forgot 4 console.log

**Comment by thomastosoni** [comment]
Check my branch with the same name, I did an update :+1:

**Pull request closed without merging**
